### ISSUE TITLE
Multiplayer issues in game

### ISSUE THREAD

**Issue by ZenithGD** [UNIZAR-30226-2022-10/quizzyWeb#5]
## Start turn call after earning a token

A start turn event is emitted when the user earns a token.

## The turn does not change when a player won 3 tokens in a row
- Because turn event was called before the players who won the tokens has made his last movement.

I think this is a known issue but i'll leave it here:

Sometimes, the multiplayer question dialog question closes before the player answers it. This might be caused by a setTimeout that isn't properly cleaned.

**Comment by Tiss971** [comment]
Start turn call after earning a token && change player turn after 3 tokens in a row issues have been fixed in commit [9fc1483](https://github.com/UNIZAR-30226-2022-10/quizzyWeb/commit/9fc148332946f1970a219c5d7129f1c8d2f36921)

Question dialog issue hasn't been fixed yet
